apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaservice
  labels:
    app: msa-banking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eureka-service
      app: msa-banking-app

  template:
    metadata:
      name: eureka-msa-pod
      labels:
        name: eureka-service
        app: msa-banking-app

    spec:
      containers:
      - name: eureka-container
        image: ${REPOSITORY_TAG}
        imagePullPolicy: Always

      imagePullSecrets:
          - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: microservices-eureka-service
  labels:
    name: eureka-service
    app: msa-banking-app

spec:
  type: LoadBalancer
  ports:
  -  protocol: TCP
     targetPort: 8761
     port: 8761

  selector:
    name: eureka-service
    app: msa-banking-app


        