server:
  port: 8761

spring:
  application:
    name: microservices-eureka-service
 
eureka:
  instance:
    hostname: microservices-eureka-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

   
# eureka:
  # server:
    # enableSelfPreservation: false
  # instance:
    # hostname: localhost
  # client:
    # registerWithEureka: false
    # fetchRegistry: false
    # serviceUrl:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
# eureka:
  # server:
    # enableSelfPreservation: false
  # instance:
    # preferIpAddress: true
  # client:
    # registerWithEureka: false
    # fetchRegistry: false
    # serviceUrl:
      # defaultZone: http://eureka-cluster-ip-service:${server.port}/eureka/
      

# eureka:
  # server:
    # enableSelfPreservation: false
  # instance:
    # preferIpAddress: true
  # client:
    # registerWithEureka: false
    # fetchRegistry: false
    # serviceUrl:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      

            





